name: Autorun Main CI

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: install boost
      run: sudo apt-get install libboost-all-dev
    - name: make
      run: make
    - name: test
      run: ./tb
